### ISSUE TITLE
Can't pip install the package anymore!

### ISSUE THREAD

**Issue by mostafazh** [soulomoon/python-throttle#3]
# Stack trace

```
$pip3 install python-throttle
Collecting python-throttle
  Downloading https://files.pythonhosted.org/packages/02/6c/a48a9fbd54740e025a01de12ec7f099d84aef0881b6f83a4c2a3a12cd499/python-throttle-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qe8fgcs4/python-throttle/setup.py", line 1, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qe8fgcs4/python-throttle/
```

# Steps to Reproduce

`$docker run --rm python:3.7 pip install python-throttle`
`$docker run --rm python:2 pip install python-throttle`

**Comment by soulomoon** [comment]
@mostafazh thank you for the issue, I am trying to fix it

**Comment by soulomoon** [comment]
@mostafazh I remove the pandoc requirement, It should now be fix 
```bash
➜ docker run --rm python:3.7 pip install python-throttle                                                           │
Collecting python-throttle                                                                                         │
  Downloading https://files.pythonhosted.org/packages/13/72/f6a7ef6cc6c1450c132ff25796ab6240f223b3fb797866cbf8c26f7│
21aa2/python-throttle-0.2.0.tar.gz                                                                                 │
Collecting redis>=3 (from python-throttle)                                                                         │
  Downloading https://files.pythonhosted.org/packages/ac/a7/cff10cc5f1180834a3ed564d148fb4329c989cbb1f2e196fc9a10fa│
07072/redis-3.2.1-py2.py3-none-any.whl (65kB)                                                                      │
Building wheels for collected packages: python-throttle                                                            │
  Building wheel for python-throttle (setup.py): started                                                           │
  Building wheel for python-throttle (setup.py): finished with status 'done'                                       │
  Stored in directory: /root/.cache/pip/wheels/f8/0f/f1/545114d01b8447d779d482efc175a3572b37f76c292f696c16         │
Successfully built python-throttle                                                                                 │
Installing collected packages: redis, python-throttle                                                              │
Successfully installed python-throttle-0.2.0 redis-3.2.1                                                           │
```

**Comment by mostafazh** [comment]
Works again, thanks @soulomoon :)
